import type { Metadata } from "next";
import {Roboto} from "next/font/google"
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
 
import "./globals.css";
 

const roboto = Roboto({
  weight: ['100','300','400','500','700','900'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      
      <body className={roboto.className}>
      <Navbar />
      <main>
        {children}
        </main>
        <Footer/>
        </body>

    </html>
  );
}
